"""
Convenient definitions of common constants.
"""


DOWNSAMPLING_STEPS = 4

IMAGE_N_CHANNELS = 3
IMAGE_N_COLUMNS = 1280
IMAGE_N_ROWS = 720

N_CONVOLUTIONS_AT_SAME_RESOLUTION = 3
N_OUTPUTS_PER_ANCHOR = 5

OUTPUT_GRID_CELL_N_ANCHORS = 3
OUTPUT_GRID_CELL_N_COLUMNS = 16  # TODO
OUTPUT_GRID_CELL_N_ROWS = 16  # TODO

OUTPUT_GRID_N_COLUMNS = int(IMAGE_N_COLUMNS / OUTPUT_GRID_CELL_N_COLUMNS)
OUTPUT_GRID_N_ROWS = int(IMAGE_N_ROWS / OUTPUT_GRID_CELL_N_ROWS)
